// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import './globals.css';

export const metadata = {
  title: 'My Todo App',
  description: 'A simple todo list application built with Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-center bg-cover sm:p-24 bg-[url("./../public/image.jpeg")] bg-no-repeat h-fit '>
        <header className="w-full p-4 text-white ">
          <h1 className="text-3xl text-center">My Todo List</h1>
        </header>
        <main className="p-6 mx-auto sm:max-w-3xl">{children}</main>
      </body>
    </html>
  );
}
